/* © 2025–2026 ClearSky Energy Solutions LLC. Proprietary and Confidential.
   scripts/guides/make-qr.js — writes the QR codes the printed guides carry
   (scripts/guides/qr/*.svg). The SVGs are committed, so building a guide
   never needs this script or its package; run it only when an address in
   CODES changes.

   Usage (the npm package "qrcode" is NOT a dependency of this repo; install
   it anywhere outside the repo and point at it):
     npm install --prefix /tmp/qr qrcode
     QRCODE=/tmp/qr/node_modules/qrcode node scripts/guides/make-qr.js

   Every code points at a front door that works for everybody, so it carries
   no ?org= and names no workspace: the app resolves the workspace from the
   signed-in work email. */
'use strict';
var fs = require('fs'), path = require('path');
/* /logic is the short front door (vercel.json redirects it to /office/app):
   easy to type, and the phone lands on the Omega Logic sign-in */
var CODES = {
  'office-app': 'https://silmarillion.clearskyomega.com/logic'
};
function load() {
  var tries = [process.env.QRCODE, 'qrcode'].filter(Boolean);
  for (var i = 0; i < tries.length; i++) { try { return require(tries[i]); } catch (e) { /* next */ } }
  console.error('make-qr: the npm package "qrcode" was not found.\n'
    + '  npm install --prefix /tmp/qr qrcode\n'
    + '  QRCODE=/tmp/qr/node_modules/qrcode node scripts/guides/make-qr.js');
  process.exit(1);
}
var QR = load(), OUT = path.join(__dirname, 'qr');
fs.mkdirSync(OUT, { recursive: true });
Object.keys(CODES).reduce(function (p, name) {
  return p.then(function () {
    /* navy on white, medium error correction, a four-module quiet zone: it
       prints on a white card, and a phone camera reads it at arm's length */
    return QR.toString(CODES[name], { type: 'svg', errorCorrectionLevel: 'M', margin: 4, color: { dark: '#0f2e3fff', light: '#ffffffff' } });
  }).then(function (svg) {
    var note = '<!-- © 2025–2026 ClearSky Energy Solutions LLC. Proprietary and Confidential.\n'
      + '     QR code for ' + CODES[name] + '\n'
      + '     Generated by scripts/guides/make-qr.js; do not edit by hand. -->\n';
    fs.writeFileSync(path.join(OUT, name + '.svg'), note + svg.trim() + '\n');
    console.log('qr/' + name + '.svg  ->  ' + CODES[name]);
  });
}, Promise.resolve()).catch(function (e) { console.error(e); process.exit(1); });
