/* © 2025–2026 ClearSky Energy Solutions LLC. Proprietary and Confidential. */
'use strict';
var test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');
var e=require('../api/_lib/fiber-evidence');
function feature(kind,eligible,geometry,more){return {type:'Feature',id:kind,geometry:geometry||{type:'LineString',coordinates:[[-88,41],[-86,41]]},properties:Object.assign({feature_kind:kind,proximity_eligible:eligible,source_id:'test',operational_status:'unknown',fiber_strands_reported:null},more||{})};}
function data(features){return {features:features,manifest:{built_at:'2026-09-18T00:00:00Z'}};}
test('empty coverage returns unknown, never no-fiber or zero capacity',function(){var r=e.screen({lat:41,lon:-87,requested_capacity_gbps:100},data([]));assert.equal(r.site_has_fiber,null);assert.equal(r.available_capacity_gbps,null);assert.equal(r.meets_requested_capacity,null);assert.equal(r.complete_national_inventory,false);});
test('a nearby confirmed-material route still cannot prove site access or spare bandwidth',function(){var r=e.screen({lat:41,lon:-87},data([feature('fiber_route',true)]));assert.equal(r.routes.length,1);assert.equal(r.site_serviceability,'unconfirmed');assert.equal(r.physical_route_diversity,'unconfirmed');});
test('planning, unknown medium and facilities never become qualifying fiber routes',function(){var r=e.screen({lat:41,lon:-87},data([feature('network_design',false),feature('telecom_route_unknown',false),feature('telecom_facility',false,{type:'Point',coordinates:[-87,41]}),feature('fiber_route',false,null,{operational_status:'planned'})]));assert.equal(r.routes.length,0);assert.equal(r.planning_routes.length,2);assert.equal(r.unknown_medium_routes.length,1);assert.equal(r.facilities.length,1);});
test('spherical distance handles antimeridian and zero-length segments',function(){assert.ok(e.segmentDistance([180,0],[179,0],[-179,0])<0.01);assert.ok(Math.abs(e.segmentDistance([0,1],[0,0],[0,0])-111195)<2);assert.ok(e.segmentDistance([2,0],[0,0],[1,0])>111190);});
test('empty, nonfinite, coercible and out-of-range coordinates fail validation',function(){[null,'',true,[],{},Infinity,'NaN',91].forEach(function(v){assert.throws(function(){e.parseRequest({lat:v,lon:0});});});assert.throws(function(){e.parseRequest({lat:0,lon:-181});});assert.throws(function(){e.parseRequest({lat:0,lon:0,radius_km:500});});});
test('route counts and truncation are explicit and distances are sorted',function(){var r=e.screen({lat:41,lon:-87,limit:1},data([feature('fiber_route',true),feature('fiber_route',true,{type:'LineString',coordinates:[[-87,41.05],[-87,41.1]]})]));assert.equal(r.counts_in_radius.routes,2);assert.equal(r.routes.length,1);assert.equal(r.results_truncated,true);});
test('bundled datasets match manifest hashes, stable IDs and the capacity evidence policy',function(){
 var root=path.join(__dirname,'../data/fiber'),m=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'))),ids=new Set();
 m.datasets.forEach(function(d){var bytes=fs.readFileSync(path.join(root,d.file));assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),d.sha256);var j=JSON.parse(bytes);assert.equal(j.features.length,d.count);j.features.forEach(function(f){assert.ok(!ids.has(f.id));ids.add(f.id);assert.match(f.properties.source_url,/^https:\/\//);assert.equal(f.properties.offered_capacity_gbps,null);assert.equal(f.properties.spare_capacity_gbps,null);if(f.properties.feature_kind==='network_design')assert.equal(f.properties.proximity_eligible,false);});});
 assert.ok(m.datasets.find(function(d){return d.file==='osm-fiber-routes.geojson';}).count>0);assert.equal(m.site_capacity_verified,false);
});
test('all release geometries are finite valid WGS84 points or lines',function(){e.load().features.forEach(function(f){var g=f.geometry;assert.ok(['Point','LineString','MultiLineString'].includes(g.type));var points=g.type==='Point'?[g.coordinates]:g.type==='LineString'?g.coordinates:g.coordinates.flat();points.forEach(function(p){assert.equal(typeof p[0],'number');assert.equal(typeof p[1],'number');assert.ok(Number.isFinite(p[0])&&Math.abs(p[0])<=180);assert.ok(Number.isFinite(p[1])&&Math.abs(p[1])<=90);});});});
