/* © 2025–2026 ClearSky Energy Solutions LLC. Proprietary and Confidential. */
'use strict';
var test=require('node:test'),assert=require('node:assert/strict'),P=require('../api/_lib/fiber-parcel'),E=require('../api/_lib/fiber-evidence'),fs=require('fs');
var outer=[[-97,32],[-96.99,32],[-96.99,32.01],[-97,32.01],[-97,32]],hole=[[-96.997,32.003],[-96.993,32.003],[-96.993,32.007],[-96.997,32.007],[-96.997,32.003]];
function boundary(rings){return {type:'Polygon',coordinates:rings||[outer]};}
function route(id,coords,eligible){return {type:'Feature',id:id,geometry:{type:'LineString',coordinates:coords},properties:{name:id,feature_kind:'fiber_route',proximity_eligible:eligible!==false,source_url:'https://example.org/source',geometry_quality:'publisher_geometry_unverified'}};}
function data(features){return {features:features,manifest:{built_at:'2026-09-19'},usaBuiltAt:'2026-09-19'};}
test('crossing, interior, touching and nearby route relations use the boundary',function(){
 var r=P.inspect({boundary:boundary(),radius_km:1},data([route('cross',[[-97.01,32.005],[-96.98,32.005]]),route('inside',[[-96.999,32.001],[-96.998,32.001]]),route('edge',[[-97,32],[-97,32.01]]),route('near',[[-96.989,32],[-96.989,32.01]])]));
 assert.equal(r.routes.length,4);assert.equal(r.routes.filter(function(x){return x.intersects_boundary_or_interior;}).length,3);assert(r.routes.find(function(x){return x.id==='near';}).mapped_distance_m>80);assert.equal(r.site_has_fiber,null);assert.equal(r.site_serviceability,'unconfirmed');assert.equal(r.available_capacity_gbps,null);assert.equal(r.complete_national_inventory,false);
});
test('a route entirely inside a hole is not a parcel crossing',function(){var r=P.inspect({boundary:boundary([outer,hole])},data([route('in-hole',[[-96.996,32.005],[-96.994,32.005]])]));assert.equal(r.routes[0].intersects_boundary_or_interior,false);assert(r.routes[0].mapped_distance_m>90);assert.equal(r.boundary.coordinates.length,2);});
test('all MultiPolygon parts are inspected; no connection is invented between them',function(){var far=outer.map(function(c){return [c[0]+.02,c[1]];}),r=P.inspect({boundary:{type:'MultiPolygon',coordinates:[[outer],[far]]}},data([route('second',[[-96.979,32.001],[-96.978,32.001]])]));assert.equal(r.routes[0].intersects_boundary_or_interior,true);assert.equal(r.boundary.coordinates.length,2);});
test('invalid coordinates, open/degenerate/self-crossing rings and hostile radius values are rejected',function(){
 for(var b of [null,{type:'LineString',coordinates:outer},boundary([outer.slice(0,-1)]),boundary([[[-97,32],[-96.99,32.01],[-96.99,32],[-97,32.01],[-97,32]]]),boundary([[[-97,32],[-97,32],[-96.99,32],[-97,32]]]),boundary([[[-97,32],[-96,32],[-96,33],[-97,33],[-97,32]]])])assert.throws(function(){P.parse({boundary:b});});
 for(var radius of [null,true,[],[1],0,6,NaN,''])assert.throws(function(){P.parse({boundary:boundary(),radius_km:radius});});
 var outsideHole=hole.map(function(c){return [c[0]+.02,c[1]];});assert.throws(function(){P.parse({boundary:boundary([outer,outsideHole])});});
});
test('planned and reference-only lines stay separate from qualifying evidence',function(){var r=P.inspect({boundary:boundary()},data([route('normal',[[-97,32],[-96.99,32]],true),route('reference',[[-97,32],[-96.99,32]],false)]));assert.equal(r.routes.length,1);assert.equal(r.context_routes.length,1);assert.equal(r.context_routes[0].proximity_eligible,false);var adapted=E.usaAdapt({properties:{category:'unknown',proximityEligible:false}});assert.equal(adapted.properties.proximity_eligible,false);});
test('display cropping splits disconnected source runs without drawing connectors',function(){var parts=P.displayParts([[0,0],[.5,.5],[2,2],[3,3],[2,0],[.5,0]],[0,0,1,1]);assert.equal(parts.length,2);assert.deepEqual(parts[0],[[0,0],[.5,.5],[2,2]]);assert.deepEqual(parts[1],[[2,0],[.5,0]]);});
test('nearby records outside limit are reported as truncated, not silently missing',function(){var features=[];for(var i=0;i<30;i++)features.push(route('r'+i,[[-97,32],[-96.99,32]]));var r=P.inspect({boundary:boundary()},data(features));assert.equal(r.counts.mapped_routes,30);assert.equal(r.routes.length,25);assert.equal(r.results_truncated,true);});
test('excessive geometry work fails explicitly rather than timing out or returning partial distances',function(){var coords=[];for(var i=0;i<210001;i++)coords.push([-96.999+i*.00000001,32.001]);assert.throws(function(){P.inspect({boundary:boundary()},data([route('large',coords)]));},function(e){return e.status===422&&/no partial result/.test(e.message);});});
test('public parcel registry and UI preserve geometry, minimize fields, and guard stale responses',function(){
 var registry=require('../data/usa-fiber/parcel-sources.json');assert.equal(registry.sources.length,5);assert.deepEqual(Array.from(new Set(registry.sources.map(function(s){return s.state;}))).sort(),['GA','IL','TX']);registry.sources.forEach(function(s){assert(/^https:\/\//.test(s.url));assert(!/owner|taxpayer/i.test(s.idField));});
 var ui=fs.readFileSync('fiber-parcel-inspector.js','utf8');assert(/outFields:s.idField/.test(ui));assert(/run!==version/.test(ui));assert(/run!==parcelVersion/.test(ui));assert(/MultiPolygon/.test(ui));assert(!/lineDistance|segmentToSegment/.test(ui),'boundary calculations remain server-side');assert(/fpResultExport.*disabled=true/.test(ui));
});
