#!/usr/bin/env node
/* ===========================================================================
   scripts/steward/data-watch.js - the state of the data layers and of the
   fiber sources the compute-siting tools depend on.
   (c) 2025-2026 ClearSky Energy Solutions LLC. Proprietary and Confidential.

   WHY DATA NEEDS A DAILY OWNER

   The grid and fiber layers in this repo are not code, they are snapshots.
   ci-industrial.js was generated by a Python script; ilshines-sites.js says
   "do not edit by hand"; data/land-listings.json says, in the file itself,
   "SEED FILE - real LandSearch listings (fetched July 14, 2026) ... Replace
   with an Apify Land.com dataset export for parcel-precise locations."

   None of that is wrong. All of it decays, and none of it decays loudly. A
   siting answer built on a year-old hosting-capacity snapshot looks exactly
   like one built on this morning's. The cost lands on whoever drove to the
   site.

   So this reports, for every data layer: how big it is, how many records,
   what generated it, what date the file itself claims, when it was last
   committed, and whether that is older than the layer's staleness budget.
   Provenance notes the file makes about itself - SEED, approximate,
   do not edit - are carried into the report verbatim, because a caveat
   written once in a header is a caveat nobody reads twice.

   FIBER is the same question with a different answer. api/fiber-proxy.js is
   a licensed vendor adapter that refuses with 503 when FIBER_VENDOR_BASE and
   FIBER_VENDOR_KEY are unset, and api/network-proximity.js scores against
   PeeringDB, the FCC broadband map and OpenStreetMap. Whether those are
   connected today is not visible from the repo, so it is asked of the
   deployment - and reported as unknown when nobody gave the steward a
   credential, rather than assumed healthy.

     node scripts/steward/data-watch.js
     node scripts/steward/data-watch.js --json
     node scripts/steward/data-watch.js --sources   also ping the free upstreams
   =========================================================================== */
'use strict';

var fs = require('fs');
var path = require('path');
var cp = require('child_process');

var ROOT = path.resolve(__dirname, '..', '..');

/* A layer's staleness budget is a judgement about how fast the world moves
   under it, not a uniform number. Hosting capacity is republished on a
   utility's own clock; land listings go stale in weeks. */
var LAYERS = [
  { file: 'data/land-listings.json',      budgetDays: 30,  what: 'for-sale land listings behind the Grid Atlas zip report' },
  { file: 'ci-industrial.js',             budgetDays: 180, what: 'commercial and industrial parcels with owner and business enrichment' },
  { file: 'ilshines-sites.js',            budgetDays: 180, what: 'Illinois Shines projects above the size floor' },
  { file: 'grid-atlas-national.js',       budgetDays: 365, what: 'national grid infrastructure extension' },
  { file: 'tenants/solela/utilities.json', budgetDays: 365, what: 'Illinois utility territories for the ComEd pipeline shell' },
  { file: 'assets/platform.json',         budgetDays: 90,  what: 'platform manifest built by scripts/build-platform-manifest.js' }
];

/* Free upstreams api/network-proximity.js scores against. Pinged only with
   --sources: they are somebody else's servers and this runs every day. */
var SOURCES = [
  { name: 'PeeringDB', url: 'https://www.peeringdb.com/api/fac?limit=1', why: 'carrier facilities and exchanges - the fiber density proxy' },
  { name: 'OpenStreetMap Overpass', url: 'https://overpass-api.de/api/status', why: 'mapped fibre, exchanges and cabinets' },
  { name: 'US Census geocoder', url: 'https://geocoding.geo.census.gov/geocoder/locations/onelineaddress?address=1600+Pennsylvania+Ave+NW+Washington+DC&benchmark=2020&format=json', why: 'the keyless geocoder every siting lookup starts with' }
];

function read(rel) {
  try { return fs.readFileSync(path.join(ROOT, rel), 'utf8'); } catch (e) { return null; }
}

/* Committed date, not mtime: in a fresh clone every mtime is checkout time,
   which would make every layer look brand new every morning. */
function lastCommitted(rel) {
  try {
    var out = cp.execSync('git log -1 --format=%cs -- ' + JSON.stringify(rel), { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
    return out || null;
  } catch (e) { return null; }
}

function daysSince(iso) {
  if (!iso) return null;
  var then = Date.parse(iso + (iso.length === 10 ? 'T00:00:00Z' : ''));
  if (isNaN(then)) return null;
  return Math.floor((Date.now() - then) / 86400000);
}

/* Layers state their own vintage in prose. Pull the first date out of the
   header so "the file says July 14, 2026" can sit next to "last committed
   2026-09-06" - when those disagree, the prose is usually the true one. */
function statedDate(head) {
  var m = /\b(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2}),\s+(\d{4})/.exec(head);
  if (m) {
    var months = { January: '01', February: '02', March: '03', April: '04', May: '05', June: '06', July: '07', August: '08', September: '09', October: '10', November: '11', December: '12' };
    return m[3] + '-' + months[m[1]] + '-' + (m[2].length === 1 ? '0' + m[2] : m[2]);
  }
  var iso = /\b(20\d{2}-\d{2}-\d{2})\b/.exec(head);
  return iso ? iso[1] : null;
}

function generator(head) {
  var m = /Generated by ([\w./-]+)/i.exec(head) || /rebuilt by ([\w./-]+)/i.exec(head) || /built by ([\w./-]+)/i.exec(head);
  return m ? m[1] : null;
}

/* Caveats the file makes about itself, carried through verbatim. */
function caveats(head) {
  var out = [];
  if (/SEED FILE/i.test(head)) out.push('declares itself a SEED FILE');
  if (/approximate|APPROXIMATE/.test(head)) out.push('coordinates or values are approximate');
  if (/do not edit by hand/i.test(head)) out.push('generated - do not edit by hand');
  if (/partial coverage|not national|no national coverage/i.test(head)) out.push('coverage is partial');
  return out;
}

function countRecords(rel, src) {
  if (/\.json$/.test(rel)) {
    try {
      var j = JSON.parse(src);
      if (j && Array.isArray(j.features)) return j.features.length + ' features';
      if (Array.isArray(j)) return j.length + ' records';
      return Object.keys(j || {}).length + ' keys';
    } catch (e) { return 'unparseable JSON'; }
  }
  /* The generated .js layers are one big array literal assigned to a window
     global. Parsing it properly means evaluating 1.5 MB of somebody else's
     data; counting the entry openings does not, and is close enough to notice
     a layer that halved overnight - which is the failure worth catching. */
  var m = src.match(/\{\s*"?(?:id|pin|name|lat|owner|zip)"?\s*:/g);
  return m ? '~' + m.length + ' entries' : 'unknown';
}

function layers() {
  return LAYERS.map(function (l) {
    var src = read(l.file);
    if (src == null) return { file: l.file, missing: true, what: l.what };
    var head = src.slice(0, 2000);
    var committed = lastCommitted(l.file);
    var stated = statedDate(head);
    var ageSource = stated || committed;
    var age = daysSince(ageSource);
    return {
      file: l.file,
      what: l.what,
      bytes: Buffer.byteLength(src),
      records: countRecords(l.file, src),
      generator: generator(head),
      statedDate: stated,
      lastCommitted: committed,
      ageDays: age,
      budgetDays: l.budgetDays,
      stale: age != null && age > l.budgetDays,
      caveats: caveats(head)
    };
  });
}

function pingSources() {
  return Promise.all(SOURCES.map(function (s) {
    var started = Date.now();
    var ctl = new AbortController();
    var timer = setTimeout(function () { ctl.abort(); }, 15000);
    return fetch(s.url, { signal: ctl.signal, headers: { 'User-Agent': 'omega-steward/1.0 (+clearskyomega.com)' } })
      .then(function (r) {
        clearTimeout(timer);
        return { name: s.name, why: s.why, ok: r.ok, status: r.status, ms: Date.now() - started };
      })
      .catch(function (e) {
        clearTimeout(timer);
        return { name: s.name, why: s.why, ok: false, status: 0, error: String(e.message || e), ms: Date.now() - started };
      });
  }));
}

/* What the repo can say about fiber without calling anything: which variables
   the licensed adapter needs, and whether this process has them. The deployed
   answer comes from probe.js, which can ask /api/fiber-proxy with a token. */
function fiberConfig() {
  var needed = ['FIBER_VENDOR_BASE', 'FIBER_VENDOR_KEY'];
  var present = needed.filter(function (v) { return !!process.env[v]; });
  return {
    adapter: 'api/fiber-proxy.js',
    needs: needed,
    presentInThisProcess: present,
    note: present.length === needed.length
      ? 'licensed fiber source is configured here'
      : 'licensed fiber source is not configured in this process. That is expected on CI - the deployment holds the variables. api/fiber-proxy answers 503 "Licensed fiber source is not connected" when they are missing, so the tools degrade to the free sources in api/network-proximity.js rather than failing.',
    freeSources: SOURCES.map(function (s) { return s.name; })
  };
}

function main() {
  var asJson = process.argv.indexOf('--json') >= 0;
  var withSources = process.argv.indexOf('--sources') >= 0;
  var ls = layers();
  var fiber = fiberConfig();

  return (withSources ? pingSources() : Promise.resolve(null)).then(function (sources) {
    var out = { checkedAt: new Date().toISOString(), layers: ls, fiber: fiber, sources: sources };
    if (asJson) { console.log(JSON.stringify(out, null, 2)); return ls.some(function (l) { return l.stale || l.missing; }) ? 1 : 0; }

    console.log('omega steward - data and fiber');
    console.log('');
    ls.forEach(function (l) {
      if (l.missing) { console.log('  MISSING  ' + l.file + '  (' + l.what + ')'); return; }
      var mark = l.stale ? 'STALE' : 'ok   ';
      console.log('  ' + mark + '  ' + l.file);
      console.log('          ' + l.what);
      console.log('          ' + (l.records) + ', ' + Math.round(l.bytes / 1024) + ' KB' +
        (l.generator ? ', from ' + l.generator : '') +
        (l.ageDays != null ? ', ' + l.ageDays + ' days old (budget ' + l.budgetDays + ')' : ', age unknown'));
      if (l.statedDate) console.log('          the file states: ' + l.statedDate + (l.lastCommitted ? ' (last committed ' + l.lastCommitted + ')' : ''));
      l.caveats.forEach(function (c) { console.log('          caveat: ' + c); });
    });
    console.log('');
    console.log('  fiber');
    console.log('          ' + fiber.note);
    if (sources) {
      console.log('');
      console.log('  upstream sources');
      sources.forEach(function (s) {
        console.log('  ' + (s.ok ? 'ok   ' : 'FAIL ') + '  ' + s.name + '  ' + (s.ok ? s.ms + 'ms' : (s.error || 'HTTP ' + s.status)));
        console.log('          ' + s.why);
      });
    }
    return ls.some(function (l) { return l.stale || l.missing; }) ? 1 : 0;
  });
}

if (require.main === module) {
  Promise.resolve(main()).then(function (c) { process.exit(c); });
}
module.exports = { layers: layers, fiberConfig: fiberConfig, pingSources: pingSources };
