#!/bin/bash
# © 2025–2026 ClearSky Energy Solutions LLC. Proprietary and Confidential.
#
# Installs the Firebase Admin service-account key into the omega-core Vercel
# project and redeploys. The key is generated by YOU in the Firebase console
# (one click); this script waits for the download, checks it is the right kind
# of file, uploads it to Vercel, and pushes a redeploy. The key's contents are
# never printed.
set -e
cd "$(dirname "$0")/.."

CONSOLE="https://console.firebase.google.com/project/clearsky-portal/settings/serviceaccounts/adminsdk"
START=$(date +%s)

echo
echo "1) A browser tab is opening on the Firebase console."
echo "   Click the blue  'Generate new private key'  button, then  'Generate'."
echo "   A file named clearsky-portal-firebase-adminsdk-....json lands in Downloads."
echo
open "$CONSOLE"
echo "   Waiting for that download…"

FILE=""
for i in $(seq 1 180); do
  FILE=$(find "$HOME/Downloads" -maxdepth 1 -name 'clearsky-portal-firebase-adminsdk*.json' -newermt "@$START" 2>/dev/null | head -1)
  [ -n "$FILE" ] && break
  sleep 2
done
if [ -z "$FILE" ]; then echo "   No key file appeared in Downloads after 6 minutes. Run this again."; exit 1; fi
echo "   Got it: $(basename "$FILE")"

node -e '
  const j = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
  if (j.type !== "service_account" || !j.private_key || !j.client_email) { console.error("   That file is not a service-account key."); process.exit(1); }
  if (j.project_id !== "clearsky-portal") { console.error("   That key is for project " + j.project_id + ", not clearsky-portal."); process.exit(1); }
  console.log("   Checked: service-account key for clearsky-portal (" + j.client_email + ")");
' "$FILE"

echo
echo "2) Replacing FIREBASE_SERVICE_ACCOUNT on Vercel (production)…"
npx -y vercel@latest env rm FIREBASE_SERVICE_ACCOUNT production --yes >/dev/null 2>&1 || true
npx -y vercel@latest env add FIREBASE_SERVICE_ACCOUNT production < "$FILE" >/dev/null
echo "   Set."

echo
echo "3) Redeploying so the functions pick it up…"
git commit -q --allow-empty -m "chore: redeploy with the Firebase Admin credential in place"
git push -q origin main
echo "   Pushed. Vercel builds in about two minutes."

for i in $(seq 1 30); do
  sleep 10
  code=$(curl -s -o /dev/null -w '%{http_code}' -X POST https://silmarillion.clearskyomega.com/api/health -H 'Authorization: Bearer not-a-token')
  [ "$code" = "401" ] && break
done

echo
echo "Done. Open the gateway and click 'Server health' — it should say Firestore is reachable."
echo "Then delete the key file from Downloads so it is not lying around:"
echo "   $FILE"
