/* © 2025–2026 ClearSky Energy Solutions LLC. Proprietary and Confidential.
   Local UI fixture only. No Firebase, QuickBooks or bank calls. */
'use strict';
var http=require('http'),fs=require('fs'),path=require('path');
var base=path.resolve(__dirname,'..'),org='cleancell.us',query='?org='+org;
var links={office:'/omega-logic'+query,factory:'/plant/'+query,customer:'/portals/customer/'+query,board:'/plant/work-orders.html'+query,logistics:'/logic-logistics.html'+query,poInbox:'/po-inbox?office=1&org='+org,urls:'/logic-urls.html'+query,manager:'/plant/manager.html'+query,catalog:'/logic-catalog.html'+query,
  start:'/customer-start.html'+query,
  customers:'/portals/customer/admin.html'+query,
  storefront:'/embed/storefront.html?k=fixture',setup:'/whitelabel-setup.html'+query,
  editor:'/editor.html',preview:'/editor.html?wlpreview='+org,mission:'/mission?view=logic&org='+org};
var commercial=require('../api/_lib/logic-policy').snapshot(100000);
var designProducts=require('../api/_lib/logic-catalog').designs({}),flow=require('../api/_lib/plant-flow').current({});
var fixture={owner:true,org:org,name:'CleanCell · LOCAL TEST DATA',active:true,products:2,links:links,
  config:{enabled:true,terms:{depositPct:30,dueDays:0},fee:{percent:0.25,fixed:0},realmId:'SANDBOX FIXTURE',itemRef:'1',accountingApproved:true},
  orders:[{id:'preview1',orderNo:'CC-TEST-001',customer:{name:'Example commercial site',email:'buyer@example.invalid'},status:'in_fulfilment',items:[{sku:'EXAMPLE-CAB',name:'Example battery cabinet (not a real catalog SKU)',qty:2}],worksOrderId:'wo_preview1',purchaseOrder:{number:'PO-EXAMPLE-1'},rep:{id:'rep_example',name:'Example rep',email:'rep@example.invalid'},delivery:{version:1,revision:1,destinations:[{id:'a',address:{name:'Example site A',line1:'1 Example St',city:'Chicago',state:'IL'},items:[{sku:'EXAMPLE-CAB',qty:2}]}],legs:[{id:'LOAD-1',destinationId:'a',carrier:'Example carrier',tracking:'TEST-BOL-1',serials:['TEST-003'],status:'picked_up',pickedUpAt:'2026-09-21T15:00:00Z',lastConfirmedLocation:{label:'Example yard, IL',at:'2026-09-21T18:00:00Z'}}]},logic:{commercial:commercial,acceptedAt:'2026-09-21',releasedAt:'2026-09-21',invoices:{deposit:{amountCents:commercial.depositCents,paidCents:commercial.depositCents,status:'paid'}},allocatedSerials:['TEST-001'],requirements:[{sku:'EXAMPLE-CAB',qty:1}],payout:{status:'awaiting_cleared_funds',sentCents:0}}},
    {id:'preview2',orderNo:'CC-TEST-002',customer:{name:'Example warehouse',email:'warehouse@example.invalid'},status:'new',items:[{sku:'EXAMPLE-CAB',qty:1}]}]};
fixture.brand=require('../api/_lib/logic-brand')({name:fixture.name});
/* Portfolio screener demo: the REAL ingest → match → quality → size → screen → finance pipeline run once, in memory, on example data. GET only. */
var PF=(function(){var R=require('../api/_lib/portfolio/run'),M=require('../api/_lib/portfolio/match'),AG=require('../api/_lib/portfolio/aggregate'),RP=require('../api/_lib/portfolio/report'),T=require('../api/_lib/portfolio/template'),pcsv=require('../api/_lib/portfolio/csv'),pxlsx=require('../api/_lib/portfolio/xlsx'),NOW='2026-09-22T12:00:00Z';
  var head=['Site ID','Site name','Street address','City','State','ZIP code','Utility','Project objective','Demand charge ($/kW-month)','Energy rate ($/kWh)','Main service rating (A)','Service voltage (V)','Phase','Available installation area (sq ft)','Transformer capacity (kVA)'].concat(T.MONTHS.map(function(m){return m+' kW';})).concat(T.MONTHS.map(function(m){return m+' kWh';}));
  function row(o){return head.map(function(h){return o[h]!=null?o[h]:'';});}
  function months(peak,kwh){var o={};T.MONTHS.forEach(function(m,i){o[m+' kW']=peak+(i>4&&i<9?120:0);o[m+' kWh']=kwh;});return o;}
  var rows=[head,row({'Site ID':'S-001','Site name':'Example cold storage','Street address':'105 Example St','City':'Chicago','State':'IL','ZIP code':'60601','Utility':'ComEd','Project objective':'Peak shaving','Demand charge ($/kW-month)':'21.5','Energy rate ($/kWh)':'0.105','Main service rating (A)':'2000','Service voltage (V)':'480','Phase':'3','Available installation area (sq ft)':'1800'}),
    row(Object.assign({'Site ID':'S-002','Site name':'Example distribution center','Street address':'220 Example Ave','City':'Joliet','State':'IL','ZIP code':'60431','Utility':'ComEd','Project objective':'Demand charge reduction','Transformer capacity (kVA)':'300'},months(360,140000))),
    row({'Site ID':'S-003','Site name':'Example retail','Street address':'9 Example Rd','City':'Naperville','State':'IL','ZIP code':'60540','Utility':'ComEd'}),
    row(Object.assign({'Site ID':'S-004','Site name':'Example plant','Street address':'40 Example Blvd','City':'Aurora','State':'IL','ZIP code':'60505','Utility':'ComEd','Project objective':'Resilience','Demand charge ($/kW-month)':'19'},months(900,400000)))];
  var iv=[];for(var i=0;i<8760;i++){var h=i%24;iv.push(i+','+(300+(h>=9&&h<=17?350:0)+40*Math.sin(i/24*Math.PI)+(h===14?120:0)).toFixed(1));}
  var uploads=[{name:'example-portfolio/sites.csv',bytes:Buffer.from(pcsv.stringify(rows))},{name:'example-portfolio/S-001/interval-8760.csv',bytes:Buffer.from('hour,kW\n'+iv.join('\n')+'\n')},{name:'example-portfolio/bills/S-002-bill-2026-01.pdf',bytes:Buffer.from('%PDF-1.4 LOCAL FIXTURE — not a real bill')},{name:'example-portfolio/bills/utility-bill-march.pdf',bytes:Buffer.from('%PDF-1.4 LOCAL FIXTURE — unmatched bill')}];
  var pack=R.intake(uploads,NOW),mem={},sites=pack.siteLists[0].sites.map(function(s){return Object.assign({},s,{documents:[],history:[{at:NOW,by:'fixture',what:'Created from sites.csv (row '+s.row+')'}],status:'uploaded',createdAt:NOW});}),byId={};
  sites.forEach(function(s){byId[s.siteId]=s;});
  var matches=M.matchFiles(pack.files.filter(function(f){return f.type!=='sitelist';}).map(function(f){return {id:f.id,name:f.name};}),sites.map(function(s){return {siteId:s.siteId,addressKey:s.addressKey,name:s.name};})),mById={};matches.forEach(function(m){mById[m.id]=m;});
  var files=pack.files.map(function(f){var m=mById[f.id]||{siteId:null,matchedBy:null,candidates:[],ambiguous:false};mem[f.id]=f.bytes;var rec={id:f.id,name:f.name,container:f.container,type:f.type,size:f.size,uploadedAt:f.uploadedAt,siteId:m.siteId,matchedBy:m.matchedBy,candidates:m.candidates,ambiguous:m.ambiguous,interval:f.interval||null};
    if(m.siteId&&byId[m.siteId])byId[m.siteId].documents.push({id:f.id,name:f.name,type:f.type,size:f.size,path:'mem:'+f.id,uploadedAt:f.uploadedAt,container:f.container,interval:f.interval||null,matchedBy:m.matchedBy});return rec;});
  var ctx={products:designProducts.filter(function(p){return !p.placeholder;}),tenantCost:{capexPerKwh:null,capexPerKw:null},listPrices:[],now:NOW,readFile:function(p){return Promise.resolve(mem[p.slice(4)]);}};
  var ready=Promise.all(sites.map(function(s){return R.processSite(s,ctx).then(function(out){Object.assign(s,out);s.history.push({at:NOW,by:'fixture',what:'Processed → '+out.status});});}));
  var demo={id:'demo-portfolio',name:'Example portfolio · LOCAL TEST DATA',status:'report_ready',problems:pack.problems,history:[{at:NOW,by:'fixture',what:'Uploaded 4 files → '+pack.files.length+' in package, '+sites.length+' sites created'}],createdAt:NOW,updatedAt:NOW,lastAnalyzedAt:NOW};
  return {ready:ready,handle:function(u,res){var b=u.searchParams,json=function(o){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(o));};
    if(b.get('template')==='xlsx'){res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition','attachment; filename="portfolio-upload-template.xlsx"');res.end(pxlsx.build(T.templateRows()));return;}
    if(b.get('template')){res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="portfolio-upload-template.csv"');res.end('﻿'+pcsv.stringify(T.templateRows()));return;}
    if(!b.get('portfolio'))return json({org:org,brand:fixture.brand,access:{active:true},products:ctx.products.length,portfolios:[{id:demo.id,name:demo.name,status:demo.status,siteCount:sites.length,summary:AG.summary(sites),updatedAt:NOW,createdAt:NOW}]});
    if(b.get('export')==='csv'){res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="portfolio-demo-results.csv"');res.end('﻿'+RP.exportCsv(sites));return;}
    if(b.get('report')==='executive'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(RP.executive(demo,sites,{brandName:fixture.name,now:NOW}));return;}
    var one=sites.filter(function(s){return s.siteId===b.get('site');})[0];
    if(b.get('report')==='site'||b.get('site')){if(!one){res.writeHead(404);return json({error:'Site not found'});}if(b.get('report')==='site'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(RP.siteReport(demo,one,{brandName:fixture.name,now:NOW}));return;}return json({portfolio:{id:demo.id,name:demo.name},site:AG.siteView(one,true),designLink:null});}
    json({portfolio:Object.assign({siteCount:sites.length},demo),files:files,reviewQueue:files.filter(function(f){return f.type!=='sitelist'&&(!f.siteId||f.ambiguous);}),sites:sites.map(function(s){return AG.siteView(s,false);}),summary:AG.summary(sites),remaining:0,access:{active:true},catalogProducts:ctx.products.length,brand:fixture.brand});}};})();
var fake='<script>window.CLEARSKY_CONFIG={};var qaUser={email:"tom@clearsky-usa.com",getIdToken:function(){return Promise.resolve("LOCAL-FIXTURE");}};var qaAuth={currentUser:qaUser,onAuthStateChanged:function(fn){setTimeout(function(){fn(qaUser);},0);}};window.firebase={apps:[{}],auth:function(){return qaAuth;}};</script>';
var server=http.createServer(function(req,res){var u=new URL(req.url,'http://localhost');res.setHeader('Cache-Control','no-store');
  if(req.method==='POST'&&u.pathname==='/api/customer-design'){var raw='';req.on('data',function(chunk){raw+=chunk;});req.on('end',function(){var b;try{b=JSON.parse(raw);}catch(e){b={};}res.setHeader('Content-Type','application/json');if(b.action!=='size'){res.writeHead(403);res.end(JSON.stringify({error:'Local preview is read-only. No live operation was performed.'}));return;}var target={module:b.module,kw:Number(b.kw),kwh:b.module==='bess'?Number(b.kw)*Number(b.hours):null,conceptOnly:true};res.end(JSON.stringify(b.module==='bess'?require('../api/_lib/logic-catalog').select({},b.sku,target):target));});return;}
  if(req.method!=='GET'){res.writeHead(403,{'Content-Type':'application/json'});res.end(JSON.stringify({error:'Local preview is read-only. No live operation was performed.'}));return;}
  if(/^\/(?:omega-[a-z0-9-]+\.(?:js|css)|editor-lite-logic\.js)$/.test(u.pathname)&&fs.existsSync(path.join(base,u.pathname.slice(1)))){res.setHeader('Content-Type',u.pathname.endsWith('.css')?'text/css':'application/javascript');res.end(fs.readFileSync(path.join(base,u.pathname.slice(1))));return;}
  if(u.pathname==='/editor.html'){res.setHeader('Content-Type','text/html');res.end(fs.readFileSync(path.join(base,'editor.html'),'utf8'));return;}
  if(u.pathname==='/api/customer-design'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({org:org,brand:{name:fixture.name,primary:'#3FAFC6'},access:{active:true,status:'trial',expiresAt:'2099-01-01T00:00:00Z',modules:['bess','solar','ev','compute']},projects:[],designProducts:designProducts}));return;}
  if(u.pathname==='/api/logic-catalog'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({org:org,owner:true,brand:{name:fixture.name},revision:0,products:[],designProducts:designProducts}));return;}
  if(u.pathname==='/api/logic-urls'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({org:org,brand:{name:fixture.name},rows:[{name:'Customer walkthrough',description:'Local fixture link',url:'http://127.0.0.1:'+server.address().port+links.start},{name:'Battery sizer',description:'No live key in fixture',url:null}]}));return;}
  if(u.pathname==='/api/logic-plant'&&!u.searchParams.has('serial')){var Board=require('../api/_lib/plant-board'),work={id:'wo_preview1',orgId:org,orderId:'preview1',orderNo:'CC-TEST-001',lineId:'main',status:'released',priority:'urgent',dueDate:'2026-09-15',assignee:'Example supervisor',managerNotes:'LOCAL TEST DATA — not a real work order',flowVersion:0,routing:flow.routing,requirements:[{sku:'EXAMPLE-CAB',qty:2}],registeredCounts:{'EXAMPLE-CAB':2},shippingUnitCount:2,releasedUnits:3,createdAt:'2026-09-10T12:00:00Z'},
    work2={id:'stock_preview',orgId:org,orderNo:'STOCK',inventory:true,lineId:'main',status:'released',priority:'low',flowVersion:0,routing:flow.routing,requirements:[{sku:'EXAMPLE-CAB',qty:1}],registeredCounts:{},createdAt:'2026-09-18T12:00:00Z'},
    work3={id:'wo_preview3',orgId:org,orderId:'preview3',orderNo:'CC-TEST-003',lineId:'main',status:'released',priority:'normal',dueDate:'2026-10-30',flowVersion:0,routing:flow.routing,requirements:[{sku:'EXAMPLE-CAB',qty:1}],registeredCounts:{'EXAMPLE-CAB':1},shippingUnitCount:1,releasedUnits:1,createdAt:'2026-09-19T12:00:00Z'},
    units={wo_preview1:[{serial:'TEST-001',woId:'wo_preview1',sku:'EXAMPLE-CAB',unitType:'cabinet',shipUnit:true,at:'elec',done:{kit:'2026-09-19T08:00:00Z',module:'2026-09-19T11:00:00Z',rack:'2026-09-20T09:30:00Z',encl:'2026-09-20T15:00:00Z'},arrivedAt:'2026-09-20T15:00:00Z',hold:null,test:null},
      {serial:'TEST-002',woId:'wo_preview1',sku:'EXAMPLE-CAB',unitType:'cabinet',shipUnit:true,at:'bms',done:{kit:'2026-09-19T08:10:00Z',module:'2026-09-19T12:00:00Z',rack:'2026-09-20T10:00:00Z',encl:'2026-09-20T16:00:00Z',elec:'2026-09-21T09:00:00Z'},arrivedAt:'2026-09-21T09:00:00Z',hold:'Cell voltage spread',holdAt:'2026-09-21T10:30:00Z',holdBy:'qa@example.invalid',ncr:'NCR-LOCAL-1',test:{result:'fail',at:'2026-09-21T10:29:00Z',station:'eol',failureCode:'V-SPREAD'}},
      {serial:'TEST-002-M1',woId:'wo_preview1',sku:'EXAMPLE-MOD',unitType:'module',parentSerial:'TEST-002',shipUnit:false,at:'module',done:{kit:'2026-09-19T08:20:00Z'},arrivedAt:'2026-09-19T08:20:00Z',hold:null,test:null}],
      stock_preview:[],wo_preview3:[{serial:'TEST-003',woId:'wo_preview3',sku:'EXAMPLE-CAB',unitType:'cabinet',shipUnit:true,at:'ready',done:{kit:1,module:1,rack:1,encl:1,elec:1,bms:1,eol:1,qa:1,pack:1},arrivedAt:'2026-09-21T14:00:00Z',hold:null,test:{result:'pass',at:'2026-09-21T12:00:00Z',station:'eol'}}]},
    works=[work3,work2,work],station={id:'station_fixture',label:'Example bench',station:'kit',lineId:'main',location:'Test bay',instructions:'LOCAL TEST DATA',active:true,revision:0};var kind=u.searchParams.get('page'),woq=u.searchParams.get('workOrder'),wsel=works.filter(function(w){return w.id===woq;})[0];res.setHeader('Content-Type','application/json');
    var Ops=require('../api/_lib/plant-ops'),rowsNow=works.map(function(w){return Board.row(w,units[w.id]||[]);}),scans=[];Object.keys(units).forEach(function(k){units[k].forEach(function(u){Object.keys(u.done||{}).forEach(function(st){var t=u.done[st];if(typeof t==='string')scans.push({at:t,ok:true,verdict:{action:'advance',to:st},stationId:'station_'+st,station:st});});if(u.test&&u.test.at)scans.push({at:u.test.at,ok:u.test.result==='pass',machine:true,test:u.test,verdict:u.test.result==='pass'?{action:'advance',to:'eol'}:{action:'hold'},stationId:'eol-rig'});if(u.holdAt)scans.push({at:u.holdAt,ok:true,control:{action:'hold'},verdict:{action:'hold'}});});});scans.push({at:new Date(Date.now()-864e5*2).toISOString(),ok:false,verdict:{reason:'out_of_sequence'},stationId:'station_pack'});
    var stockUnits=[{serial:'STOCK-0001',sku:'EXAMPLE-CAB',at:'ready',shipUnit:true,hold:null},{serial:'STOCK-0002',sku:'EXAMPLE-CAB',at:'ready',shipUnit:true,hold:'Cosmetic'}],common={owner:true,flow:flow,name:fixture.name,brand:{name:fixture.name},asOf:new Date().toISOString(),rows:rowsNow,limited:false,unitsLimited:false,links:{office:links.office,factory:links.factory,manager:'/plant/manager'+query,board:links.board,logistics:links.logistics}};
    var Attention=require('../api/_lib/plant-attention'),Stats=require('../api/_lib/plant-stats'),allUnits=[].concat.apply([],Object.keys(units).map(function(k){return units[k];})),stationsNow=[Object.assign({},station,{lastSeenAt:new Date(Date.now()-30*3600000).toISOString()}),{id:'phone_fixture',label:'Roaming phone',station:'*',roaming:true,lineId:'main',location:'',instructions:'',active:true,revision:0,lastSeenAt:null}];
    if(u.searchParams.get('map')){res.end(JSON.stringify({name:fixture.name,owner:true,brand:{name:fixture.name},map:Object.assign(Stats.stationMap(flow.routing,allUnits,Date.now(),{shipUnitsOnly:true}),{steps:[],lines:flow.lines,sampledLimit:false})}));return;}
    res.end(JSON.stringify(kind==='attention'?Object.assign(Attention.attention(allUnits,stationsNow,flow.routing,new Date().toISOString(),{}),{name:fixture.name,owner:true,brand:{name:fixture.name},sampled:allUnits.length,sampledLimit:false,links:common.links}):kind==='board'?common:kind==='ops'?Object.assign(common,{floor:Ops.floor(scans,new Date().toISOString(),14),queues:Ops.queues(rowsNow),demand:Ops.demand(rowsNow),stock:Ops.stock(stockUnits),completed:Ops.completed(rowsNow),scansLimited:false,stockLimited:false}):kind?{rows:kind==='works'?works:kind==='stations'?stationsNow:kind==='units'?allUnits:[],next:null}:woq?(wsel?{workOrder:wsel,units:units[wsel.id]||[],limited:false,board:Board.row(wsel,units[wsel.id]||[]),activity:Board.activity(units[wsel.id]||[],wsel,60)}:{error:'Work order not found'}):{owner:true,flow:flow,name:fixture.name,brand:{name:fixture.name},worksOrders:works,units:[]}));return;}
  if(u.pathname==='/api/logic-logistics'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({brand:{name:fixture.name},notice:'LOCAL FIXTURE — manual shipment evidence ledger.',limited:false,orders:[{id:'preview1',orderNo:'CC-TEST-001',status:'in_fulfilment',poNumber:'PO-EXAMPLE-1',items:[{sku:'EXAMPLE-CAB',name:'Example battery cabinet',qty:2}],destinations:[{id:'a',address:{name:'Example site A',line1:'1 Example St',city:'Chicago',state:'IL'},items:[{sku:'EXAMPLE-CAB',qty:2}]}],revision:1,legs:[{id:'LOAD-1',destinationId:'a',carrier:'Example carrier',tracking:'TEST-BOL-1',serials:['TEST-003'],status:'picked_up',pickedUpAt:'2026-09-21T15:00:00Z',deliveredAt:null,lastConfirmedLocation:{label:'Example yard, IL',at:'2026-09-21T18:00:00Z'},receipts:[]}]}]}));return;}
  if(u.pathname==='/api/customer-portal'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({org:org,brand:{name:fixture.name,primary:'#3FAFC6'},links:{start:links.start,account:links.customer,design:links.customer+'#design',storefront:null},editorLite:{monthlyPriceCents:79900,checkoutAvailable:false}}));return;}
  if(u.pathname==='/api/buyers'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(u.searchParams.has('email')?{company:'Example buyer · LOCAL FIXTURE',email:'buyer@example.invalid',terms:{depositPct:30,dueDays:0},orders:fixture.orders}:{org:org,name:fixture.name,portalUrl:links.customer,customers:[{id:'test',company:'Example buyer · LOCAL FIXTURE',status:'active',terms:{depositPct:30,dueDays:0},users:[{email:'buyer@example.invalid',name:'Example contact',activated:false}]}]}));return;}
  if(u.pathname==='/api/my-account'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({customerId:'company_example',company:'Example buyer · LOCAL FIXTURE',accountType:'company',since:'2026-08-01T00:00:00Z',rep:{name:'Example rep',email:'rep@example.invalid'},plan:'free',status:'active',you:{email:'buyer@example.invalid',name:'Example contact',role:'owner'},users:[{email:'buyer@example.invalid',name:'Example contact',role:'owner'},{email:'colleague@example.invalid',name:'Example colleague',role:'user'}],terms:{depositPct:30,dueDays:0,poRequired:true},agreements:[],orders:1}));return;}
  if(u.pathname==='/api/my-orders'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({orders:fixture.orders.map(function(o){return require('../api/_lib/portal').publicOrder(o);})}));return;}
  if(u.pathname==='/api/logic-office'){res.setHeader('Content-Type','application/json');var S=require('../api/_lib/office-stage'),officeOrders=fixture.orders.map(function(o){return Object.assign({},o,{stage:S.stageOf(o),totalCents:o.logic?o.logic.commercial.totalCents:null,createdAt:'2026-09-20T12:00:00Z'});});res.end(JSON.stringify(u.searchParams.get('org')?Object.assign({},fixture,{orders:officeOrders,totals:S.totals(officeOrders),finance:S.finance(officeOrders,true),intake:{review:1,needsInfo:0,declined:1}}):{owner:true,tenants:[{name:fixture.name,orgId:org,status:'LOCAL FIXTURE',links:links}]}));return;}
  if(u.pathname==='/api/logic-plant'){res.setHeader('Content-Type','application/json');var testUnit={serial:'TEST-001',sku:'EXAMPLE-CAB',at:'ready',shipUnit:true,unitType:'cabinet',orderNo:'CC-TEST-001',trace:{lot:'LOCAL-TEST-LOT'},test:{result:'pass',measurements:{fixtureOnly:1}}};res.end(JSON.stringify(u.searchParams.get('serial')?{unit:testUnit,genealogy:[testUnit],events:[{at:'LOCAL FIXTURE',station:'eol',verdict:{say:'Example pass record'},test:testUnit.test}]}:{name:fixture.name,worksOrders:[{id:'wo_preview1',orderId:'preview1',orderNo:'CC-TEST-001',status:'awaiting_serials',requirements:[{sku:'EXAMPLE-CAB',qty:1}]}],units:[testUnit]}));return;}
  if(u.pathname==='/api/customer-portfolio'){PF.ready.then(function(){PF.handle(u,res);});return;}
  if(u.pathname==='/portals/customer/portfolio.js'){res.setHeader('Content-Type','application/javascript');res.end(fs.readFileSync(path.join(base,'portals/customer/portfolio.js')));return;}
  if(u.pathname.indexOf('/api/')===0){res.writeHead(404,{'Content-Type':'application/json'});res.end(JSON.stringify({error:'Not available in the local read-only fixture.'}));return;}
  var page=['/logic-catalog.html','/logic-urls.html','/logic-logistics.html','/logic-inventory.html','/logic-materials.html','/logic-settings.html','/po-inbox.html','/plant/manager.html','/plant/station.html','/plant/work-orders.html','/plant/app.html'].indexOf(u.pathname)>=0?u.pathname.slice(1):u.pathname==='/po-inbox'?'po-inbox.html':u.pathname==='/plant/app'?'plant/app.html':u.pathname==='/plant/manager'?'plant/manager.html':u.pathname==='/editor-lite.html'?'editor-lite.html':u.pathname==='/customer-start.html'?'customer-start.html':u.pathname==='/portals/customer/admin.html'?'portals/customer/admin.html':u.pathname==='/portals/customer/'?'portals/customer/index.html':u.pathname.indexOf('/plant')===0?'plant/index.html':'omega-logic.html';
  var html=fs.readFileSync(path.join(base,page),'utf8').replace(/<script\s+src="([^"]+)"><\/script>/g,function(tag,src){return ['/omega-logic-theme.js','/editor-lite-logic.js','/portals/customer/portfolio.js'].indexOf(src)>=0?tag:'';});
  html=html.replace('</head>',fake+'</head>');res.setHeader('Content-Type','text/html');res.end(html);
});
server.listen(Number(process.argv[2]||8798),'127.0.0.1',function(){console.log('LOCAL FIXTURE ONLY — http://127.0.0.1:'+server.address().port+'/omega-logic?org=cleancell.us&order=preview1');});
